apiVersion: v1
kind: Service
metadata:
  name: frontend1
  labels:
    app: guestbook1
    tier: frontend1
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  type: LoadBalancer
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: guestbook1
    tier: frontend1
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: frontend1
spec:
  selector:
    matchLabels:
      app: guestbook1
      tier: frontend1
  replicas: 1
  template:
    metadata:
      labels:
        app: guestbook1
        tier: frontend1
    spec:
      containers:
      - name: php-redis
        image: ramkri123/web-server
        resources:
          requests:
            cpu: 1000m
            memory: 16777216Ki
            sgx.intel.com/enclave: 1
            sgx.intel.com/epc: 16777216Ki
          limits:
            sgx.intel.com/enclave: 1
            sgx.intel.com/epc: 16777216Ki
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          # value: env
        ports:
        - containerPort: 8080
      nodeSelector:
        node.kubernetes.io/instance-type: Standard_DC4ds_v3
