apiVersion: v1
kind: ConfigMap
metadata:
  name: vmbc-configmap-telegraf
data:
  {{- $tplString :=  include "telegraf.urlConcatenation"  . }}
  {{ (.Files.Glob "telegraf/telegraf.conf").AsConfig | replace "$PULL_ENDPOINTS"  $tplString | indent 12 }}
{{- $certFile := "telegraf/certs/push_metrics_http/telegraf.crt" }}
{{- $certs := $.Files.Get $certFile }}
{{ if $certs }}
binaryData:
  ca.crt: {{ $.Files.Get "telegraf/certs/push_metrics_http/telegraf.crt" | b64enc }}
{{- end }}