apiVersion: v1
kind: Service
metadata:
  name: replica-2
  labels:
    app: replica-2-concord
    blockchainId: {{ .Values.global.blockchainId }}
spec:
  type: ClusterIP
  ports:
    - name: 'tcp-3501'
      port: 3501
      protocol: TCP
      targetPort: 3501
    - name: '5458'
      port: 5458
      protocol: TCP
      targetPort: 5458
    - name: 'tcp-9891'
      port: 9891
      protocol: TCP
      targetPort: 9891
  selector:
    app: replica-2-concord
    blockchainId: {{ .Values.global.blockchainId }}

