apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmbc-deployment-replica-3-concord
  labels:
    app: replica-3-concord
    blockchainId: {{ .Values.global.blockchainId }}
spec:
  replicas: {{ .Values.global.replicaCount }}
  strategy:
    type: Recreate
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: replica-3-concord
      blockchainId: {{ .Values.global.blockchainId }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/ConfigMap-replica-3-concord.yaml") . | sha256sum }}
      labels:
        app: replica-3-concord
        blockchainId: {{ .Values.global.blockchainId }}
    spec:
      securityContext:
        fsGroup: 1244
        fsGroupChangePolicy: OnRootMismatch
      imagePullSecrets:
        - name: vmwathena-regcred
      volumes:
        {{- $configfile := "fluentd/config/fluent.conf" }}
        {{- $fluent := $.Files.Get $configfile }}
        {{ if $fluent }}
        - name: vmbc-docker-log
          hostPath:
            path: /var/log/pods
        - name: vmbc-docker-lib
          hostPath:
            path: /var/lib/docker/containers
        - name: vmbc-configmap-fluentd
          configMap:
            name: vmbc-configmap-fluentd
        {{ end }}
        - name: concord-replica-3-volume
          persistentVolumeClaim:
            claimName: concord-pvc-{{ .Values.global.blockchainId }}-replica-3
        - name: config-common-volume
          configMap:
            name: vmbc-configmap-common
        - name: config-concord-volume
          configMap:
            name: vmbc-configmap-replica-3-concord
        - name: secret-volume
          secret:
            secretName: vmbc-secret-replica-3-concord
        - name: config-init-container-command-script-volume
          configMap:
            name: init-container-command-script-config
            defaultMode: 0777
      containers:
        - name: replica-3-concord
          image: {{ include "concord.image" . }}
          imagePullPolicy: IfNotPresent
          {{- include "concord.command" . | indent 10 }}
          ports:
            - containerPort: 5458
              protocol: TCP
            - containerPort: 50051
              protocol: TCP
            - name: "tcp-9891"
              containerPort: 9891
              protocol: TCP
            - name: "tcp-3501"
              containerPort: 3501
              protocol: TCP
            - name: "udp-3501"
              containerPort: 3501
              protocol: UDP
            - name: "tcp-3502"
              containerPort: 3502
              protocol: TCP
            - name: "udp-3502"
              containerPort: 3502
              protocol: UDP
            - name: "tcp-3503"
              containerPort: 3503
              protocol: TCP
            - name: "udp-3503"
              containerPort: 3503
              protocol: UDP
            - name: "tcp-3504"
              containerPort: 3504
              protocol: TCP
            - name: "udp-3504"
              containerPort: 3504
              protocol: UDP
            - name: "tcp-3505"
              containerPort: 3505
              protocol: TCP
            - name: "udp-3505"
              containerPort: 3505
              protocol: UDP
          resources:
            limits:
              cpu: "{{ .Values.resources.replica.cpuLimit | default .Values.resources.replica.defaultCpuLimit }}"
              memory: "{{ .Values.resources.replica.memoryLimit | default .Values.resources.replica.defaultMemoryLimit }}"
            requests:
              cpu: "{{ .Values.resources.replica.cpuRequest | default .Values.resources.replica.defaultCpuRequest }}"
              memory: "{{ .Values.resources.replica.memoryRequest | default .Values.resources.replica.defaultMemoryRequest }}"
          volumeMounts:
            - name: concord-replica-3-volume
              mountPath: /concord/rocksdbdata
              subPath: {{.Release.Namespace}}/{{.Values.global.blockchainId}}/replica-3/rocksdbdata
            - name: concord-replica-3-volume
              mountPath: /concord/log
              subPath: {{.Release.Namespace}}/{{.Values.global.blockchainId}}/replica-3/log
            - name: concord-replica-3-volume
              mountPath: /concord/config-generated
              subPath: {{.Release.Namespace}}/{{.Values.global.blockchainId}}/replica-3/config-generated
            - name: concord-replica-3-volume
              mountPath: /concord/config-local
              subPath: {{.Release.Namespace}}/{{.Values.global.blockchainId}}/replica-3/config-local
            - name: concord-replica-3-volume
              mountPath: /concord/config-local/tls_certs/
              subPath: {{.Release.Namespace}}/{{.Values.global.blockchainId}}/replica-3/config-local/tls_certs/
            ##########################################
            #           config file volumes          #
            ##########################################
            ### Common files
            # genesis file
            {{- $genesisfile := "replica-3/config/concord/config-public/genesis.json" }}
            {{- $genesisfilePrefixRemoved := $genesisfile | replace "replica-3/config" "" }}
            - name: config-common-volume
              mountPath: {{ $genesisfilePrefixRemoved }}
              subPath: genesis-file
            # principals locations
            {{- $principalslocationsfile := "replica-3/config/concord/config-public/transaction_signing_keys/principals.locations.json" }}
            {{- $principalslocationsfilePrefixRemoved := $principalslocationsfile | replace "replica-3/config/concord/config-public/transaction_signing_keys" "concord/transaction_signing_keys" }}
            - name: config-common-volume
              mountPath: {{ $principalslocationsfilePrefixRemoved }}
              subPath: principals-locations-file
            ### component-specific files
            # deployment config file
            {{- $depconfigfile := "replica-3/config/concord/config-local/deployment.config" }}
            {{- $depconfigfilePrefixRemoved := $depconfigfile | replace "replica-3/config" "" }}
            - name: config-concord-volume
              mountPath: {{ $depconfigfilePrefixRemoved }}
              subPath: deployment-config-file
            # secrets config file
            {{- $secretsconfigfile := "replica-3/config/concord/config-local/secrets.config" }}
            {{- $secretsconfigfilePrefixRemoved := $secretsconfigfile | replace "replica-3/config" "" }}
            - name: config-concord-volume
              mountPath: {{ $secretsconfigfilePrefixRemoved }}
              subPath: secrets-config-file
            # application config file
            {{- $applicationconfigfile := "replica-3/config/concord/config-local/application.config" }}
            {{- $applicationconfigfilePrefixRemoved := $applicationconfigfile | replace "replica-3/config" "" }}
            - name: config-concord-volume
              mountPath: {{ $applicationconfigfilePrefixRemoved }}
              subPath: application-config-file
            ##########################################
            #           Secrets volumes              #
            ##########################################
            # transaction signing public key
            {{- range $path, $_ := .Files.Glob "replica-3/config/concord/config-public/transaction_signing_keys/*/transaction_signing_pub.pem" }}
            {{- $prefixRemoved := $path | replace "replica-3/config/concord/config-public/transaction_signing_keys" "concord/transaction_signing_keys" }}
            - name: secret-volume
              mountPath: {{ $prefixRemoved }}
              subPath: {{ $path | replace "/" "-" }}
            {{- end }}
            # operator public key
            {{- $operatorpublickey := "replica-3/config/concord/config-public/operator_pub.pem" }}
            {{- $operatorpublickeyPrefixRemoved := $operatorpublickey | replace "replica-3/config" "" }}
            - name: config-concord-volume
              mountPath: {{ $operatorpublickeyPrefixRemoved }}
              subPath: operator-public-key-file
        {{- $configfile := "fluentd/config/fluent.conf" }}
        {{- $fluent := $.Files.Get $configfile }}
        {{ if $fluent }}
        - name: fluentd
          image: {{ include "fluentd.image" . }}
          imagePullPolicy: IfNotPresent
          env:
            - name: MULTI_LOGGING_ENABLED
              value: "true"
            - name: SERVICE_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: SERVICE_NODE_NAME
              value: replica-3
            - name: SERVICE_KIND_NAME
              value: "concord"
            - name: LOGGING_URL
              value: {{ .Values.logManagement.endpoint_1.url }}
          volumeMounts:
            - name: vmbc-docker-log
              mountPath: /vmbc/logs/pods
              readOnly: false
            - name: vmbc-docker-lib
              mountPath: /var/lib/docker/containers
              readOnly: false
            - name: vmbc-configmap-fluentd
              mountPath: /fluentd/etc/fluent.conf
              subPath: fluent.conf
            {{- $certs:= .Files.Glob "fluentd/config/certs/*.crt" }}
            {{ if $certs }}
            - name: vmbc-configmap-fluentd
              mountPath: /fluentd/certs
            {{ end }}
        {{ end }}
      initContainers:
        {{- $configfile := "fluentd/config/fluent.conf" }}
        {{- $fluent := $.Files.Get $configfile }}
        - name: init-container
          image: {{ include "concord.image" . }}
          command: ["/bin/bash", "-ec", "/init-container/script/init-container-script-config-file "]
          env:
            - name: CONFIG_DIR
              value: {{.Release.Namespace}}/{{ .Values.global.blockchainId }}/replica-3
            - name: CONFIG_OVERRIDE
              value: "{{ .Values.global.config.configOverride }}"
            - name: CONCORD_VOLUME
              value: "concord-replica-3-volume"
          volumeMounts:
            - mountPath: /config
              name: concord-replica-3-volume
            ##########################################
            #           config file volumes          #
            ##########################################
            ### Common files
            # cert files
            {{- range $path, $_ := .Files.Glob "replica-3/config/concord/config-local/tls_certs/*/node.cert" }}
            {{- $prefixRemoved := $path | replace "replica-3/config" "" }}
            {{- $key := $path | replace "replica-3/config/concord/config-local" "common" | replace "/" "-" }}
            - name: config-common-volume
              mountPath: {{ $prefixRemoved }}
              subPath: {{ $key }}
            {{- end }}
            ##########################################
            #           Secrets volumes              #
            ##########################################
            # cert private keys
            {{- range $path, $_ := .Files.Glob "replica-3/config/concord/config-local/tls_certs/*/*.pem" }}
            {{- $prefixRemoved := $path | replace "replica-3/config" "" }}
            - name: secret-volume
              mountPath: {{ $prefixRemoved }}
              subPath: {{ $path | replace "/" "-" }}
            {{- end }}
            - name: config-init-container-command-script-volume
              mountPath: /init-container/script/
          resources:
            limits:
              cpu: "{{ .Values.resources.initContainer.cpuLimit }}"
              memory: "{{ .Values.resources.initContainer.memoryLimit }}"
            requests:
              cpu: "{{ .Values.resources.initContainer.cpuRequest }}"
              memory: "{{ .Values.resources.initContainer.memoryRequest }}"
