apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: concord-pvc-{{ .Values.global.blockchainId }}-replica-2
  labels:
    blockchainId: {{ .Values.global.blockchainId }}
spec:
  storageClassName: "{{ .Values.storageClassNames.replica.replica2 | default .Values.global.storageClassName}}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.resources.replica.storageRequest | default .Values.resources.replica.defaultStorageRequest }}"