{{ if .Values.global.imageCredentials.username }}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: vmwathena-regcred
  labels:
    blockchainId: {{ .Values.global.blockchainId }}
data:
  .dockerconfigjson: {{ include "common.docker.config.json" ( dict "imageCredentials" .Values.global.imageCredentials) }}
{{- end }}